---
title: "About"
---

## Background
Joyce is a current UBC MDS graduate student with a BA in Music Theory, and a career path that has taken her everywhere. She's worked in retail, education, banking, entertainment, events, and the public service. 

## Why data science
Despite the wide range of jobs, the same questions kept resurfacing: What insights can be extracted from it? How can those insights be communicated persuasively? How can systems outlast the people who build them? And how can AI and automation make work faster and more accurate, freeing up time for deeper analysis?

After more than a decade of trying to learn on her own, Joyce decided to enrolled in UBC's Master of Data Science program. She's interested in statistics, modelling, and the process of turning messy data into something meaningful. The learning curve is steep, but she's enjoying the challenge and has been continually impressed by her instructors and cohort.

## Outside of Data

Joyce leans into her "granny hobbies" that include cooking, movies, reading, knitting, and arts and crafts, and visiting museums.

She top-rope climbs and is working toward climbing 10s with the goal of learning how to lead by the summer of 2027. Her ultimate dream is to be able to climb outdoors in different countries as she travels.

Please congratulate Joyce on recently becoming a long-distance owner of a stray cat! “Trash Kitty” was found eating scraps from the bin behind her brother’s London flat, and after only four days of whispering sweet promises of a warm bed -- and four cans of tuna-- the cat finally wandered into their home where he established himself as their newest and most adorable family menace.


